#cloud-config
users:
  - name: ${ssh_username}
    groups: [sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${public_key}

ssh_pwauth: false
disable_root: true

package_update: true
packages:
  - open-vm-tools
  - wget
  - ntpdate

runcmd:
  - systemctl enable --now open-vm-tools || true
  - ntpdate -u pool.ntp.org || true
