---
app_dir: /opt/iac-webapp
app_compose_file: "{{ app_dir }}/docker-compose.yml"
docker_users:
  - "{{ ansible_user }}"
docker_apt_release: "{{ 'noble' if (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 26) else ansible_distribution_release }}"
