services:
  web:
    image: nginx:1.27-alpine
    container_name: iac-hybrid-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro

  whoami:
    image: traefik/whoami:v1.10
    container_name: iac-hybrid-whoami
    restart: unless-stopped
    ports:
      - "8080:80"

